# generated by fastapi-codegen:
#   filename:  safuamiAPI(1).yaml
#   timestamp: 2023-12-23T00:00:17+00:00

from __future__ import annotations

from typing import Union

from fastapi import Path

from models import (
    Access,
    AccessTurnstile,
    Authentication,
    CodeVerification,
    Credentials,
    ElectronicTurnstiles,
    Error,
    FaceRegitry,
    ForgotPassword,
    Profile,
    ProfileUpdate,
    SavePictures,
    TokenSession,
    Turnstile,
    TurnstileUpdate,
    User,
    Email
)
