# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2023-12-20T21:34:22+00:00

from __future__ import annotations

from typing import Union

from fastapi import Path

from models import (
    AccessTurnstileTurnstileIdUserUserIdPostRequest,
    AccessTurnstileTurnstileIdUserUserIdPostResponse,
    AccessTurnstileTurnstileIdUserUserIdPostResponse1,
    AccessTurnstileTurnstileIdUserUserIdPostResponse2,
    AccessTurnstileTurnstileIdUserUserIdPostResponse3,
    AccessTurnstileTurnstileIdUserUserIdPostResponse4,
    ForgotPasswordPostRequest,
    LoginPostRequest,
    LoginPostResponse,
    LoginPostResponse1,
    LoginPostResponse2,
    LoginPostResponse3,
    TurnstilesGetResponse,
    TurnstilesTurnstileIdGetResponse,
    UsersPostRequest,
    UsersPostResponse,
    UsersPostResponse1,
    UsersUserIdAccessGetResponse,
    UsersUserIdAccessGetResponse1,
    UsersUserIdAccessGetResponse2,
    UsersUserIdAccessGetResponse3,
    UsersUserIdGetResponse,
    UsersUserIdGetResponse1,
    UsersUserIdGetResponse2,
    UsersUserIdGetResponse3,
    UsersUserIdPatchRequest,
    UsersUserIdPatchResponse,
    UsersUserIdPatchResponse1,
    UsersUserIdPatchResponse2,
    UsersUserIdPatchResponse3,
    UsersUserIdPatchResponse4,
    UsersUserIdPicturesGetResponse,
    UsersUserIdPicturesGetResponse1,
    UsersUserIdPicturesPostRequest,
    UsersUserIdPicturesPostResponse,
    UsersUserIdPicturesPostResponse1,
    UsersUserIdPicturesPostResponse2,
    UsersUserIdPicturesPostResponse3,
    UsersUserIdPicturesPostResponse4,
    UsersUserIdVerifyCodeConfirmationPostRequest,
    UsersUserIdVerifyCodeConfirmationPostResponse,
    UsersUserIdVerifyCodeConfirmationPostResponse1,
    UsersUserIdVerifyCodeConfirmationPostResponse2,
    UsersUserIdVerifyCodeConfirmationPostResponse3,
)
