# generated by fastapi-codegen:
#   filename:  safuamiAPI(1).yaml
#   timestamp: 2023-12-23T00:00:17+00:00

from __future__ import annotations

from fastapi import FastAPI

from routers import access, turnstile, user

app = FastAPI(
    version='2.5',
    title='safuamiAPI',
    description='safUAMI API docs',
    termsOfService='https://softminds.com/terms',
    contact={
        'name': 'softminds',
        'url': 'https://softminds.com',
        'email': 'contact@softminds.com',
    },
    license={'url': 'https://www.apache.org/licenses/LICENSE-2.0.html', 'name': 'MIT'},
    servers=[{'url': 'http://localhost:8000', 'description': 'Live Server'}],
)

app.include_router(access.router)
app.include_router(turnstile.router)
app.include_router(user.router)


@app.get("/")
async def root():
    return {"message": "Gateway of the App"}
