# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2023-12-20T21:34:22+00:00

from __future__ import annotations

from fastapi import FastAPI

from routers import access, turnstile, user

app = FastAPI(
    title='safuamiAPI',
    description='safUAMI API docs',
    contact={
        'name': 'softminds',
        'url': 'https://softminds.com',
        'email': 'contact@softminds.com',
    },
    version='1.3.1',
    servers=[
        {'url': 'http://localhost:3000', 'description': 'Live Server', 'variables': {}}
    ],
)

app.include_router(access.router)
app.include_router(turnstile.router)
app.include_router(user.router)


@app.get("/")
async def root():
    return {"message": "Gateway of the App"}
