# generated by fastapi-codegen:
#   filename:  safAPiv2OAS30.yaml
#   timestamp: 2023-12-21T06:46:14+00:00

from __future__ import annotations

from fastapi import APIRouter

from dependencies import *

router = APIRouter(tags=['access'])


@router.get(
    '/access/users/{user_id}',
    response_model=None,
    responses={
        '202': {'model': AccessUsersUserIdGetResponse},
        '401': {'model': AccessUsersUserIdGetResponse1},
        '403': {'model': AccessUsersUserIdGetResponse2},
        '404': {'model': AccessUsersUserIdGetResponse3},
    },
    tags=['access'],
)
def get_access_turnstiles(user_id: int = Path(..., alias='userId')) -> Union[
    None,
    AccessUsersUserIdGetResponse,
    AccessUsersUserIdGetResponse1,
    AccessUsersUserIdGetResponse2,
    AccessUsersUserIdGetResponse3,
]:
    """
    get-access-turnstiles
    """
    pass


@router.post(
    '/access/users/{user_id}/turnstiles/{turnstile_id}',
    response_model=AccessUsersUserIdTurnstilesTurnstileIdPostResponse,
    responses={
        '400': {'model': AccessUsersUserIdTurnstilesTurnstileIdPostResponse1},
        '403': {'model': AccessUsersUserIdTurnstilesTurnstileIdPostResponse2},
        '408': {'model': AccessUsersUserIdTurnstilesTurnstileIdPostResponse3},
        '503': {'model': AccessUsersUserIdTurnstilesTurnstileIdPostResponse4},
    },
    tags=['access'],
)
def post_access_turnstile_turnstile_id_user_user_id(
    turnstile_id: int = Path(..., alias='turnstileId'),
    user_id: int = Path(..., alias='userId'),
    content__type: ContentType2 = Header(..., alias='Content-Type'),
    file: UploadFile = ...,
) -> Union[
    AccessUsersUserIdTurnstilesTurnstileIdPostResponse,
    AccessUsersUserIdTurnstilesTurnstileIdPostResponse1,
    AccessUsersUserIdTurnstilesTurnstileIdPostResponse2,
    AccessUsersUserIdTurnstilesTurnstileIdPostResponse3,
    AccessUsersUserIdTurnstilesTurnstileIdPostResponse4,
]:
    """
    post-access-turnstile-turnstileId-user-userId
    """
    pass
