# generated by fastapi-codegen:
#   filename:  safuamiAPI(1).yaml
#   timestamp: 2023-12-23T00:00:17+00:00

from __future__ import annotations

from fastapi import APIRouter

from dependencies import *

router = APIRouter(tags=['access'])


@router.get(
    '/access/users/{user_id}',
    response_model=None,
    responses={
        '202': {'model': AccessTurnstile},
        '401': {'model': Error},
        '403': {'model': Error},
        '404': {'model': Error},
    },
    tags=['access'],
)
def get_access_turnstiles(
    user_id: int = Path(..., alias='userId')
) -> Union[None, AccessTurnstile, Error]:
    """
    Conect to turnstile
    """
    pass


@router.post(
    '/access/users/{user_id}/turnstiles/{turnstile_id}',
    response_model=Access,
    responses={
        '400': {'model': Error},
        '403': {'model': Error},
        '408': {'model': Error},
        '503': {'model': Error},
    },
    tags=['access'],
)
def post_access_turnstile_turnstile_id_user_user_id(
    turnstile_id: int = Path(..., alias='turnstileId'),
    user_id: int = Path(..., alias='userId'),
    body: Authentication = None,
) -> Union[Access, Error]:
    """
    Authentication
    """
    pass
