# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2023-12-20T21:34:22+00:00

from __future__ import annotations

from fastapi import APIRouter

from ..dependencies import *

router = APIRouter(tags=['access'])


@router.post(
    '/access/turnstile/{turnstile_id}/user/{user_id}',
    response_model=AccessTurnstileTurnstileIdUserUserIdPostResponse,
    responses={
        '400': {'model': AccessTurnstileTurnstileIdUserUserIdPostResponse1},
        '403': {'model': AccessTurnstileTurnstileIdUserUserIdPostResponse2},
        '408': {'model': AccessTurnstileTurnstileIdUserUserIdPostResponse3},
        '503': {'model': AccessTurnstileTurnstileIdUserUserIdPostResponse4},
    },
    tags=['access'],
)
def post_access_turnstile_turnstile_id_user_user_id(
    turnstile_id: int = Path(..., alias='turnstileId'),
    user_id: int = Path(..., alias='userId'),
    body: AccessTurnstileTurnstileIdUserUserIdPostRequest = None,
) -> Union[
    AccessTurnstileTurnstileIdUserUserIdPostResponse,
    AccessTurnstileTurnstileIdUserUserIdPostResponse1,
    AccessTurnstileTurnstileIdUserUserIdPostResponse2,
    AccessTurnstileTurnstileIdUserUserIdPostResponse3,
    AccessTurnstileTurnstileIdUserUserIdPostResponse4,
]:
    """
    post-access-turnstile-turnstileId-user-userId
    """
    pass


@router.get(
    '/users/{user_id}/access',
    response_model=None,
    responses={
        '202': {'model': UsersUserIdAccessGetResponse},
        '401': {'model': UsersUserIdAccessGetResponse1},
        '403': {'model': UsersUserIdAccessGetResponse2},
        '404': {'model': UsersUserIdAccessGetResponse3},
    },
    tags=['access'],
)
def get_access_turnstiles(user_id: int = Path(..., alias='userId')) -> Union[
    None,
    UsersUserIdAccessGetResponse,
    UsersUserIdAccessGetResponse1,
    UsersUserIdAccessGetResponse2,
    UsersUserIdAccessGetResponse3,
]:
    """
    get-access-turnstiles
    """
    pass
