# generated by fastapi-codegen:
#   filename:  safuamiAPI(1).yaml
#   timestamp: 2023-12-23T00:00:17+00:00

from __future__ import annotations

from fastapi import APIRouter

from dependencies import *

router = APIRouter(tags=['turnstile'])


@router.get('/turnstiles', response_model=ElectronicTurnstiles, tags=['turnstile'])
def get_turnstiles() -> ElectronicTurnstiles:
    """
    Recover Turnstiles
    """
    pass


@router.post(
    '/turnstiles',
    response_model=None,
    responses={
        '400': {'model': Error},
        '401': {'model': Error},
        '500': {'model': Error},
    },
    tags=['turnstile'],
)
def post_turnstiles(body: Turnstile = None) -> Union[None, Error]:
    """
    New turnstile
    """
    pass


@router.get(
    '/turnstiles/{turnstile_id}',
    response_model=Turnstile,
    responses={
        '403': {'model': Error},
        '404': {'model': Error},
        '500': {'model': Error},
        '503': {'model': Error},
    },
    tags=['turnstile'],
)
def get_turnstiles_turnstile_id(
    turnstile_id: int = Path(..., alias='turnstileId')
) -> Union[Turnstile, Error]:
    """
    Recover turnstile
    """
    pass


@router.patch(
    '/turnstiles/{turnstile_id}',
    response_model=Turnstile,
    responses={
        '401': {'model': Error},
        '403': {'model': Error},
        '404': {'model': Error},
    },
    tags=['turnstile'],
)
def patch_turnstiles_turnstile_id(
    turnstile_id: int = Path(..., alias='turnstileId'), body: TurnstileUpdate = None
) -> Union[Turnstile, Error]:
    """
    Update Turnstile information
    """
    pass


@router.delete(
    '/turnstiles/{turnstile_id}',
    response_model=None,
    responses={'400': {'model': Error}, '404': {'model': Error}},
    tags=['turnstile'],
)
def delete_turnstiles_turnstile_id(
    turnstile_id: int = Path(..., alias='turnstileId')
) -> Union[None, Error]:
    """
    Delete turnstile
    """
    pass


@router.put(
    '/turnstiles/{turnstile_id}',
    response_model=None,
    responses={
        '401': {'model': Error},
        '403': {'model': Error},
        '404': {'model': Error},
    },
    tags=['turnstile'],
)
def put_turnstiles_turnstile_id(
    turnstile_id: int = Path(..., alias='turnstileId'), body: TurnstileUpdate = None
) -> Union[None, Error]:
    """
    Update turnstile information
    """
    pass
