# generated by fastapi-codegen:
#   filename:  safuamiAPI(1).yaml
#   timestamp: 2023-12-23T00:00:17+00:00

from __future__ import annotations

from fastapi import APIRouter

from dependencies import *

from services.turnstile import *


router = APIRouter(tags=['turnstile'])


@router.get('/turnstiles', response_model=ElectronicTurnstiles, tags=['turnstile'])
def find_all_turnstiles() -> ElectronicTurnstiles:
    """
    Recover Turnstiles
    """
    return find_all()


@router.post(
    '/turnstiles',
    response_model= Union[None, Error],
    responses={
        '400': {'model': Error},
        '401': {'model': Error},
        '500': {'model': Error},
    },
    tags=['turnstile'],
)
def create_turnstile(body: Turnstile = None) -> Union[None, Error]:
    """
    New turnstile
    """
    
    return create(body)


@router.get(
    '/turnstiles/{turnstileId}',
    response_model= Union[Turnstile, Error],
    responses={
        '403': {'model': Error},
        '404': {'model': Error},
        '500': {'model': Error},
        '503': {'model': Error},
    },
    tags=['turnstile'],
)
def find_turnstile(
    turnstileId: str = Path(..., alias='turnstileId')
) -> Union[Turnstile, Error]:
    """
    Recover turnstile
    """
    return find_by_id(turnstileId)


@router.patch(
    '/turnstiles/{turnstileId}',
    response_model=Union[Turnstile, Error],
    responses={
        '401': {'model': Error},
        '403': {'model': Error},
        '404': {'model': Error},
    },
    tags=['turnstile'],
)
def update_turnstile_by(
    turnstileId: int = Path(..., alias='turnstileId'), body: TurnstileUpdate = None
) -> Union[Turnstile, Error]:
    """
    Update Turnstile information
    """
    return update_state(body,turnstileId)


@router.delete(
    '/turnstiles/{turnstileId}',
    response_model=Union[None, Error],
    responses={'400': {'model': Error}, '404': {'model': Error}},
    tags=['turnstile'],
)
def delete_turnstile(
    turnstileId: str = Path(..., alias='turnstileId')
) -> Union[None, Error]:
    """
    Delete turnstile
    """
    return remove(turnstileId)


@router.put(
    '/turnstiles/{turnstileId}',
    response_model=Union[None, Error],
    responses={
        '401': {'model': Error},
        '403': {'model': Error},
        '404': {'model': Error},
    },
    tags=['turnstile'],
)
def update_turnstile(
    turnstileId: int = Path(..., alias='turnstileId'), body: TurnstileUpdate = None
) -> Union[None, Error]:
    """
    Update turnstile information
    """
    pass
