# generated by fastapi-codegen:
#   filename:  safAPiv2OAS30.yaml
#   timestamp: 2023-12-21T06:46:14+00:00

from __future__ import annotations

from fastapi import APIRouter

from dependencies import *

router = APIRouter(tags=['turnstile'])


@router.get('/turnstiles', response_model=TurnstilesGetResponse, tags=['turnstile'])
def get_turnstiles() -> TurnstilesGetResponse:
    """
    get-turnstiles
    """
    pass


@router.post(
    '/turnstiles',
    response_model=None,
    responses={
        '400': {'model': TurnstilesPostResponse},
        '401': {'model': TurnstilesPostResponse1},
        '500': {'model': TurnstilesPostResponse2},
    },
    tags=['turnstile'],
)
def post_turnstiles(
    body: TurnstilesPostRequest = None,
) -> Union[
    None, TurnstilesPostResponse, TurnstilesPostResponse1, TurnstilesPostResponse2
]:
    """
    post-turnstiles
    """
    pass


@router.get(
    '/turnstiles/{turnstile_id}',
    response_model=TurnstilesTurnstileIdGetResponse,
    tags=['turnstile'],
)
def get_turnstiles_turnstile_id(
    turnstile_id: int = Path(..., alias='turnstileId')
) -> TurnstilesTurnstileIdGetResponse:
    """
    get-turnstiles-turnstileId
    """
    pass


@router.patch(
    '/turnstiles/{turnstile_id}',
    response_model=TurnstilesTurnstileIdPatchResponse,
    responses={
        '401': {'model': TurnstilesTurnstileIdPatchResponse1},
        '403': {'model': TurnstilesTurnstileIdPatchResponse2},
        '404': {'model': TurnstilesTurnstileIdPatchResponse3},
    },
    tags=['turnstile'],
)
def patch_turnstiles_turnstile_id(
    turnstile_id: int = Path(..., alias='turnstileId'),
    body: TurnstilesTurnstileIdPatchRequest = None,
) -> Union[
    TurnstilesTurnstileIdPatchResponse,
    TurnstilesTurnstileIdPatchResponse1,
    TurnstilesTurnstileIdPatchResponse2,
    TurnstilesTurnstileIdPatchResponse3,
]:
    """
    patch-turnstiles-turnstileId
    """
    pass


@router.delete(
    '/turnstiles/{turnstile_id}',
    response_model=None,
    responses={
        '400': {'model': TurnstilesTurnstileIdDeleteResponse},
        '404': {'model': TurnstilesTurnstileIdDeleteResponse1},
    },
    tags=['turnstile'],
)
def delete_turnstiles_turnstile_id(
    turnstile_id: int = Path(..., alias='turnstileId')
) -> Union[
    None, TurnstilesTurnstileIdDeleteResponse, TurnstilesTurnstileIdDeleteResponse1
]:
    """
    delete-turnstiles-turnstileId
    """
    pass
