# generated by fastapi-codegen:
#   filename:  safuamiAPI(1).yaml
#   timestamp: 2023-12-23T00:00:17+00:00

from __future__ import annotations

from fastapi import APIRouter

from dependencies import *

from services.user import *

router = APIRouter(tags=['user'])


@router.post('/forgotPassword', response_model=None, tags=['user'])
def post_forgot_password(body: ForgotPassword = None) -> None:
    """
    Reset password
    """
    pass


@router.post(
    '/login',
    response_model=Union[TokenSession, Error],
    responses={
        '400': {'model': Error},
        '404': {'model': Error},
        '503': {'model': Error},
    },
    tags=['user'],
)
async def post_login(body: Credentials = None) -> Union[TokenSession, Error]:
    """
    Login
    """
    return login(body)


@router.post(
    '/users',
    response_model=TokenSession,
    responses={'400': {'model': Error}},
    tags=['user'],
)
async def create_account(body: Credentials = None) -> Union[TokenSession, Error]:
    """
    User registration
    """
    return create_user(body)


@router.get(
    '/users/{userId}',
    response_model=Profile,
    responses={
        '401': {'model': Error},
        '403': {'model': Error},
        '404': {'model': Error},
    },
    tags=['user'],
)
def get_users_userId(
    userId: str = Path(..., alias='userId')
) -> Union[Profile, Error]:
    """
    Recover user
    """
    pass


@router.delete(
    '/users/{userId}',
    response_model=None,
    responses={'400': {'model': Error}, '404': {'model': Error}},
    tags=['user'],
)
def delete_users_userId(
    userId: str = Path(..., alias='userId')
) -> Union[None, Error]:
    """
    Delete account
    """
    pass


@router.patch(
    '/users/{userId}',
    response_model=Profile,
    responses={
        '401': {'model': Error},
        '403': {'model': Error},
        '404': {'model': Error},
    },
    tags=['user'],
)
def patch_users_userId(
    userId: str = Path(..., alias='userId'), body: ProfileUpdate = None
) -> Union[Profile, Error]:
    """
    Modify a User
    """
    pass


@router.put(
    '/users/{userId}',
    response_model=Union[Profile, Error],
    responses={
        '401': {'model': Error},
        '403': {'model': Error},
        '404': {'model': Error},
    },
    tags=['user'],
)
async def put_users_userId(
    userId: str = Path(..., alias='userId'), body: ProfileUpdate = None
) -> Union[Profile, Error]:
    """
    Update a user
    """
    #body['userId'] = userId
    return update_info_by_block(body,userId)
    #print(userId)
    #return Error(message="erro",code=401)


@router.get(
    '/users/{userId}/pictures',
    response_model=FaceRegitry,
    responses={'404': {'model': Error}},
    tags=['user'],
)
def get_users_userId_pictures(
    userId: str = Path(..., alias='userId')
) -> Union[FaceRegitry, Error]:
    """
    Existence of facial register
    """
    pass


@router.post(
    '/users/{userId}/pictures',
    response_model=None,
    responses={
        '201': {'model': FaceRegitry},
        '400': {'model': Error},
        '401': {'model': Error},
        '403': {'model': Error},
        '404': {'model': Error},
    },
    tags=['user'],
)
def post_users_userId_pictures(
    userId: str = Path(..., alias='userId'), body: SavePictures = None
) -> Union[None, FaceRegitry, Error]:
    """
    Facial registration request
    """
    pass


@router.post(
    '/users/{userId}/sendConfirmationCode',
    response_model=None,
    responses={
        '401': {'model': Error},
        '403': {'model': Error},
        '404': {'model': Error},
    },
    tags=['user'],
)
def post_users_userId_send_confirmation_code(
    userId: str = Path(..., alias='userId')
) -> Union[None, Error]:
    """
    Send code confirmation email
    """
    pass


@router.post(
    '/users/{userId}/verifyCodeConfirmation',
    response_model=None,
    responses={
        '400': {'model': Error},
        '401': {'model': Error},
        '403': {'model': Error},
        '404': {'model': Error},
    },
    tags=['user'],
)
def post_users_userId_verify_code_confirmation(
    userId: str = Path(..., alias='userId'), body: CodeVerification = None
) -> Union[None, Error]:
    """
    Verication email
    """
    pass


@router.get('/users')
def get_users():
    #return usersEntity(data_base.user.find())
    return "users"